[package]

name = "getting-started-spinning-square"
version = "0.1.0"
authors = [ "Joe Levin <joe.levin@gmail.com>" ]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.24.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.28.0"
piston2d-opengl_graphics = "0.31.0"